# Generated by Django 3.2.3 on 2021-09-05 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_account_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('is_user', models.BooleanField(default=False)),
                ('date', models.DateField(default='2021-08-16')),
                ('time', models.DateField(auto_now_add=True)),
                ('url', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
