# Generated by Django 3.2.3 on 2021-10-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_picture',
            field=models.CharField(default='', max_length=255),
        ),
    ]
