# Generated by Django 3.2.3 on 2021-10-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_alter_funfact_touristic_place'),
        ('users', '0011_account_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_picture',
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('touristic_place', 'user')},
        ),
    ]
