# Generated by Django 3.2.3 on 2021-10-09 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('funfact_id', models.AutoField(primary_key=True, serialize=False)),
                ('fact', models.CharField(default='', max_length=255)),
                ('touristic_place', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='places.touristicplace')),
            ],
        ),
    ]
