# Generated by Django 3.2.3 on 2021-10-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_funfact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristicplace',
            name='long_info',
            field=models.TextField(),
        ),
    ]
