# Generated by Django 3.2.3 on 2021-10-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_touristicplace_long_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturetouristicplace',
            name='touristic_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='touristicplace', to='places.touristicplace'),
        ),
    ]
