# Generated by Django 3.2.3 on 2021-10-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_auto_20211018_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funfact',
            name='touristic_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='funfacts', to='places.touristicplace'),
        ),
    ]
